export const creativeStack = Object.freeze([
  {
    id: 'view-transitions',
    name: 'View Transition API',
    layer: 'navigation',
    status: 'native',
    priority: 'high',
    bundle: false,
    use: 'Route/shared-element morphs without turning navigation into a slideshow.',
    url: 'https://developer.mozilla.org/en-US/docs/Web/API/View_Transition_API',
  },
  {
    id: 'waapi',
    name: 'Web Animations API',
    layer: 'motion',
    status: 'native',
    priority: 'high',
    bundle: false,
    use: 'Small stateful DOM motion when CSS is not enough and a library would be wasteful.',
    url: 'https://developer.mozilla.org/en-US/docs/Web/API/Web_Animations_API',
  },
  {
    id: 'gsap',
    name: 'GSAP',
    layer: 'motion',
    status: 'active',
    priority: 'high',
    bundle: true,
    use: 'Authored timelines, SVG choreography and meaningful scroll/state sequences.',
    url: 'https://gsap.com/',
  },
  {
    id: 'motion-v',
    name: 'Motion for Vue',
    layer: 'motion',
    status: 'candidate',
    priority: 'medium',
    bundle: false,
    use: 'Vue-native gestures, springs and shared layout motion when that API is a better fit than GSAP.',
    url: 'https://motion.dev/docs/vue',
  },
  {
    id: 'animejs',
    name: 'Anime.js',
    layer: 'motion',
    status: 'candidate',
    priority: 'medium',
    bundle: false,
    use: 'Compact timeline/SVG/WAAPI experiments; do not duplicate GSAP without a reason.',
    url: 'https://animejs.com/',
  },
  {
    id: 'theatre',
    name: 'Theatre.js',
    layer: 'motion-authoring',
    status: 'candidate',
    priority: 'medium',
    bundle: false,
    use: 'Browser-authored cinematic timelines for rare scenes that benefit from a dope-sheet/graph editor.',
    url: 'https://www.theatrejs.com/',
  },
  {
    id: 'lenis',
    name: 'Lenis',
    layer: 'scroll',
    status: 'candidate',
    priority: 'low',
    bundle: false,
    use: 'Scroll/WebGL synchronization only if native scrolling cannot deliver the intended scene.',
    url: 'https://github.com/darkroomengineering/lenis',
  },
  {
    id: 'pts',
    name: 'Pts.js',
    layer: 'math-geometry',
    status: 'candidate',
    priority: 'high',
    bundle: false,
    use: 'Points, vectors, geometry, fields and technical drawing-like generative systems.',
    url: 'https://ptsjs.org/',
  },
  {
    id: 'p5',
    name: 'p5.js',
    layer: 'creative-coding',
    status: 'candidate',
    priority: 'high',
    bundle: false,
    use: 'Fast math/noise/particle/pixel sketches — the grown-up descendant of for-loop star exercises.',
    url: 'https://p5js.org/',
  },
  {
    id: 'two',
    name: 'Two.js',
    layer: 'vector-2d',
    status: 'candidate',
    priority: 'low',
    bundle: false,
    use: 'Renderer-agnostic SVG/Canvas/WebGL vector motion when simple shapes dominate.',
    url: 'https://two.js.org/',
  },
  {
    id: 'paper',
    name: 'Paper.js',
    layer: 'vector-2d',
    status: 'candidate',
    priority: 'medium',
    bundle: false,
    use: 'Bezier/path geometry and Illustrator-like vector scripting for diagrams and authored shapes.',
    url: 'https://paperjs.org/',
  },
  {
    id: 'canvas-sketch',
    name: 'canvas-sketch',
    layer: 'generative-art',
    status: 'reference',
    priority: 'low',
    bundle: false,
    use: 'Generative-art workflow/reference library; more useful for experiments than core UI.',
    url: 'https://github.com/mattdesl/canvas-sketch',
  },
  {
    id: 'pixi',
    name: 'PixiJS',
    layer: 'pixel-2d-gpu',
    status: 'candidate',
    priority: 'high',
    bundle: false,
    use: 'Pixel scenes, sprites, filters and EFSS PDE / Kemirkent-style interactive artifacts.',
    url: 'https://pixijs.com/',
  },
  {
    id: 'ralph-gpu',
    name: 'ralph-gpu',
    layer: 'webgpu',
    status: 'experimental',
    priority: 'high',
    bundle: false,
    use: 'Small WGSL/WebGPU shader experiments, particles and compute-driven procedural fields.',
    url: 'https://github.com/vercel-labs/ralph-gpu',
  },
  {
    id: 'three-tsl',
    name: 'Three.js / TSL',
    layer: 'webgpu-3d',
    status: 'candidate',
    priority: 'medium',
    bundle: false,
    use: 'TSL shader graphs, WebGPU/WebGL backends and real 3D only when an artifact genuinely earns it.',
    url: 'https://threejs.org/docs/TSL.html',
  },
  {
    id: 'ogl',
    name: 'OGL',
    layer: 'webgl',
    status: 'candidate',
    priority: 'medium',
    bundle: false,
    use: 'Minimal WebGL/shader layer when Three.js would be excessive.',
    url: 'https://github.com/oframe/ogl',
  },
  {
    id: 'regl',
    name: 'regl',
    layer: 'webgl',
    status: 'candidate',
    priority: 'low',
    bundle: false,
    use: 'Functional WebGL/GPGPU experiments where explicit GPU state and math are the point.',
    url: 'https://github.com/regl-project/regl',
  },
  {
    id: 'hydra',
    name: 'Hydra',
    layer: 'live-visuals',
    status: 'candidate',
    priority: 'medium',
    bundle: false,
    use: 'Music-lab video synthesis, feedback and live-coded visual experiments — not site-wide UI.',
    url: 'https://hydra.ojack.xyz/',
  },
  {
    id: 'web-audio',
    name: 'Web Audio API',
    layer: 'audio',
    status: 'native',
    priority: 'high',
    bundle: false,
    use: 'Real audio analysis and reactive visuals for music instead of decorative fake waveforms.',
    url: 'https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API',
  },
  {
    id: 'rive',
    name: 'Rive',
    layer: 'vector-runtime',
    status: 'candidate',
    priority: 'low',
    bundle: false,
    use: 'State-machine/vector animation when a deliberately authored reusable character/UI animation needs it.',
    url: 'https://rive.app/docs/runtimes/web/web-js',
  },
])

export const creativeLabTracks = Object.freeze([
  {
    id: 'math',
    label: 'MATH / GEOMETRY',
    tools: ['Pts.js', 'p5.js', 'Paper.js'],
    note: 'points · vectors · sin/cos · noise',
  },
  {
    id: 'gpu',
    label: 'PIXEL / GPU',
    tools: ['PixiJS', 'ralph-gpu', 'Three TSL', 'OGL'],
    note: 'pixels · shaders · compute · fields',
  },
  {
    id: 'motion',
    label: 'MOTION / STATE',
    tools: ['GSAP', 'View Transitions', 'Theatre.js', 'Motion'],
    note: 'morph · timeline · gesture · state',
  },
])
